FROM python:3.9-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends gcc python3-dev && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir mlflow==2.8.1 pymysql

WORKDIR /app
VOLUME /mlruns

EXPOSE 5000

CMD ["mlflow", "server", "--host", "0.0.0.0"]